# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wakeup.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wakeup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwakeup.proto\x12\x08wakemeup\"2\n\rWakeUpRequest\x12\x13\n\x0bscript_name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\"F\n\x0eWakeUpResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nprocess_id\x18\x03 \x01(\x05\x32S\n\rWakeUpService\x12\x42\n\rTriggerScript\x12\x17.wakemeup.WakeUpRequest\x1a\x18.wakemeup.WakeUpResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wakeup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WAKEUPREQUEST']._serialized_start=26
  _globals['_WAKEUPREQUEST']._serialized_end=76
  _globals['_WAKEUPRESPONSE']._serialized_start=78
  _globals['_WAKEUPRESPONSE']._serialized_end=148
  _globals['_WAKEUPSERVICE']._serialized_start=150
  _globals['_WAKEUPSERVICE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
